### ISSUE TITLE
NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z - 0.4.1,  0.4.2

### ISSUE THREAD

**Issue by toby5box** [tpolecat/doobie#568]
This reminds me of the crash I had with wrong version of **sbt**.

I don't know what I changed to trigger this. 

```
java.lang.NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z
	at scala.reflect.internal.TypeDebugging$typeDebug$.<init>(TypeDebugging.scala:62)
	at scala.reflect.internal.SymbolTable.typeDebug$lzycompute$1(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.typeDebug(SymbolTable.scala:16)
	at scala.reflect.runtime.JavaUniverseForce.force(JavaUniverseForce.scala:54)
	at scala.reflect.runtime.JavaUniverseForce.force$(JavaUniverseForce.scala:6)
	at scala.reflect.runtime.JavaUniverse.force(JavaUniverse.scala:16)
	at scala.reflect.runtime.JavaUniverse.init(JavaUniverse.scala:147)
	at scala.reflect.runtime.JavaUniverse.<init>(JavaUniverse.scala:78)
	at scala.reflect.runtime.package$.universe$lzycompute(package.scala:17)
	at scala.reflect.runtime.package$.universe(package.scala:17)
	at doobie.util.meta$MetaInstances.$init$(meta.scala:410)
	at doobie.util.meta$Meta$.<init>(meta.scala:209)
	at doobie.util.meta$Meta$.<clinit>(meta.scala)
	at doobie.imports$.<init>(imports.scala:82)
	at doobie.imports$.<clinit>(imports.scala)
```

**Comment by toby5box** [comment]
OK so reading https://gitter.im/typelevel/scala?at=59825319210ac269204b61ca it seems that the jump to sbt 0.13.15 fixed #562 only by coincidence.

**Comment by toby5box** [comment]
Reading https://gitter.im/typelevel/scala?at=597b6c851c8697534a6ae897

**Comment by tpolecat** [comment]
Hell. So it's not working with sbt 0.13.15? Do you have "org.scala-lang" anywhere in your build definition?

**Comment by toby5box** [comment]
No. But this doesn't look like a statically deterministic bug or moving from 0.13.13 to 0.13.15 would have fixed it permanently, eh?

**Comment by tpolecat** [comment]
So, how are you running? Is this `sbt run` or have you deployed elsewhere?

**Comment by toby5box** [comment]
`tomcat:start` … locally.

**Comment by toby5box** [comment]
I'll see if I can get a minimal test case happening.

**Comment by tpolecat** [comment]
Can you `show tomcat:start::fullClasspath` or however tf you do that?

**Comment by tpolecat** [comment]
I have some time today and you're a VIP so I'll see what I can do if you can get a repro.

**Comment by toby5box** [comment]
I'll do my best here. This uses the xsbt web plugin, so the invoking command is:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -cp /Volumes/ElCap/Users/toby/.ivy2/cache/com.github.jsimone/webapp-runner/jars/webapp-runner-8.5.9.0.jar webapp.runner.launch.Main --port 8080 /Volumes/FiveBox/ljlaw/ljlaw-service/target/webapp
```

Which makes me think maybe you can use this?

```
$ ls -1 target/webapp/WEB-INF/lib/
alpn-api-1.1.2.v20150522.jar
argonaut_2.12-6.2.jar
blaze-core_2.12-0.12.5.jar
blaze-http_2.12-0.12.5.jar
cats-core_2.12-0.9.0.jar
cats-kernel_2.12-0.9.0.jar
cats-macros_2.12-0.9.0.jar
commons-codec-1.10.jar
doobie-core_2.12-0.4.1.jar
doobie-postgres_2.12-0.4.1.jar
flyway-core-4.2.0.jar
fs2-cats_2.12-0.3.0.jar
fs2-core_2.12-0.9.7.jar
fs2-io_2.12-0.9.5.jar
fs2-scalaz_2.12-0.2.0.jar
grizzled-slf4j_2.12-1.3.1.jar
hpack-v1.0.1.jar
http4s-argonaut_2.12-0.17.0-M3.jar
http4s-blaze-core_2.12-0.17.0-M3.jar
http4s-blaze-server_2.12-0.17.0-M3.jar
http4s-core_2.12-0.17.0-M3.jar
http4s-dsl_2.12-0.17.0-M3.jar
http4s-jawn_2.12-0.17.0-M3.jar
http4s-server-metrics_2.12-0.17.0-M3.jar
http4s-server_2.12-0.17.0-M3.jar
http4s-servlet_2.12-0.17.0-M3.jar
http4s-tomcat_2.12-0.17.0-M3.jar
http4s-websocket_2.12-0.1.6.jar
jackson-annotations-2.6.0.jar
jackson-core-2.6.6.jar
jackson-databind-2.6.6.jar
jawn-fs2_2.12-0.10.1.jar
jawn-parser_2.12-0.10.3.jar
jbcrypt-0.4.jar
joda-time-2.9.9.jar
ljlawservice_2.12-0.1-SNAPSHOT.jar
log4s_2.12-1.3.4.jar
logback-classic-1.2.3.jar
logback-core-1.2.3.jar
machinist_2.12-0.6.1.jar
macro-compat_2.12-1.1.1.jar
metrics-core-3.0.2.jar
metrics-core-3.2.0.jar
metrics-json-3.2.0.jar
postgresql-42.1.3.jar
scala-library-2.12.1.jar
scala-library-2.12.3.jar
scala-reflect-2.12.3.jar
scala-xml_2.12-1.0.5.jar
scalaz-concurrent_2.12-7.2.7.jar
scalaz-core_2.12-7.2.7.jar
scalaz-effect_2.12-7.2.7.jar
scalaz-stream_2.12-0.8.6a.jar
scodec-bits_2.12-1.1.4.jar
shapeless_2.12-2.3.2.jar
simulacrum_2.12-0.10.0.jar
slf4j-api-1.7.25.jar
sourcecode_2.12-0.1.3.jar
tomcat-annotations-api-8.5.15.jar
tomcat-api-8.5.15.jar
tomcat-catalina-8.5.15.jar
tomcat-coyote-8.5.15.jar
tomcat-el-api-8.5.15.jar
tomcat-jaspic-api-8.5.15.jar
tomcat-jni-8.5.15.jar
tomcat-jsp-api-8.5.15.jar
tomcat-juli-8.5.15.jar
tomcat-servlet-api-8.5.15.jar
tomcat-util-8.5.15.jar
tomcat-util-scan-8.5.15.jar
```

**Comment by toby5box** [comment]
That's not just detritus; if I `rm -fr target` and `tomcat:start` I get the same situation and exception. Does that help?

**Comment by toby5box** [comment]
I think I've narrowed it down to `"ch.qos.logback" % "logback-classic" % "1.2.3"` dependency. With this in place, I get the crash reliably on a web request that tries to invoke the transactor. With this dependency removed, there is no crash.

```
[toby@macpro doobie-crash]$ curl localhost:8080/
[toby@macpro doobie-crash]$ ls target/webapp/WEB-INF/lib/ > no-crash
[toby@macpro doobie-crash]$ curl localhost:8080/
[toby@macpro doobie-crash]$ ls target/webapp/WEB-INF/lib/ > crash
[toby@macpro doobie-crash]$ diff no-crash crash
22a23,24
> logback-classic-1.2.3.jar
> logback-core-1.2.3.jar
36c38
< slf4j-api-1.7.21.jar
---
> slf4j-api-1.7.25.jar
```

**Comment by toby5box** [comment]
My minimised `build.sbt` is:

```
scalaVersion := "2.12.3"

//scalacOptions := Seq("-Ypartial-unification", "-feature", "-language:higherKinds", "-language:postfixOps")

val http4sVersion = "0.17.0-M3"

libraryDependencies ++= Seq(
  "org.http4s" %% "http4s-dsl"            % http4sVersion,
  "org.http4s" %% "http4s-blaze-server"   % http4sVersion,
  "org.http4s" %% "http4s-tomcat"         % http4sVersion,
  "javax.servlet" % "javax.servlet-api" % "3.1.0" % "provided",
  "org.tpolecat" %% "doobie-core" % "0.4.2",
  "co.fs2" %% "fs2-core" % "0.9.7",
  "co.fs2" %% "fs2-scalaz" % "0.2.0"
  , "ch.qos.logback" % "logback-classic" % "1.2.3" // <--- smoking gun
  //"org.postgresql" % "postgresql" % "42.1.3",
)

enablePlugins(TomcatPlugin)
```

I can supply the whole project if it helps.

**Comment by tpolecat** [comment]
Ok, great. Thanks for all the info. It's my night off from bedtime duty so I'll take a look after work.

/cc @milessabin if you're interested. I won't be offended if you unsubscribe.

**Comment by toby5box** [comment]
I'm still a bit confused why it broke-worked-broke, because that dep has always been in place.

**Comment by toby5box** [comment]
OK, and of course it wasn't that easy. I went back to the other project, nixed that particular dep, and it still crashes. I guess I'll have to repeat the process of elimination on those deps.

**Comment by toby5box** [comment]
I've reverted to 2.11.11 (which worked 100% with my deps, good work everyone) and the bug goes away.

**Comment by nigredo-tori** [comment]
I've got bit by this problem today. `sbt-dependency-graph` pointed to `org.http4s` packages which seem to depend on Typelevel `scala-library`: https://mvnrepository.com/artifact/org.http4s/http4s-core_2.12/0.17.0-RC1 . So we get two libraries with the same-ish API in the classpath, and the first one of those is used (hence non-determinism). Doobie was just unfortunate enough to trigger the newer API.

As a temporary workaround, switching to typelevel scala seems to work. Reverting to older http4s versions should probably do the trick, too.

**Comment by tpolecat** [comment]
Ok @toby5box did you try `excludeDependencies += "org.typelevel" % "scala-library"`? Discussed at :point_up: [August 21, 2017 9:32 PM](https://gitter.im/sbt/sbt?at=599bb3d6bc46472974abef05)

**Comment by tpolecat** [comment]
track https://github.com/typelevel/scala/issues/166

**Comment by toby5box** [comment]
@tpolecat  That seems to work nicely, thanks.

**Comment by tpolecat** [comment]
doobie isn't using the typelevel compiler now so i think we can close this
