### ISSUE TITLE
Failures after upgradine to cats-effect 1.0.0

### ISSUE THREAD

**Issue by anne-nelson** [tpolecat/doobie#774]
I'm getting a failure from Doobie when running my tests after upgrading to cats-effect 1.0.0 from 0.10.1 . I couldn't find anything on the microsite about what version of cats-effect Doobie was compatible with, but my doobie imports/versions are below.

```
"org.tpolecat" %% "doobie-core"     % "0.5.3"
"org.tpolecat" %% "doobie-postgres" % "0.5.3"
"org.tpolecat" %% "doobie-hikari"   % "0.5.3"
```

There a multiple tests that are failing, and all extend `DoobieTypecheckSpec` and fail upon initialisation.

```
[info] code.MyClassSpec *** ABORTED ***
[info] java.lang.NoSuchMethodError: cats.effect.IO$.ioConcurrentEffect()Lcats/effect/ConcurrentEffect;
[info]   at doobie.scalatest.IOChecker.$init$(Checker.scala:77)
[info]   at code.MyClassSpec.<init>(MySpec.scala:9)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:301)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:291)
```

**Comment by tpolecat** [comment]
It won't work. You need to wait for 0.6.x which will use cats-effect 1.0.0 and fs2 1.0.0 … the whole ecosystem has to upgrade.
