### ISSUE TITLE
Scala 2.13: Block result was adapted via implicit conversion (method apply) taking a by-name parameter

### ISSUE THREAD

**Issue by alonsodomin** [tpolecat/doobie#1513]
Facing the following compilation error in Scala 2.13.6:

```
[error] [...]/cron4s/modules/doobie/src/test/scala/cron4s/doobie/DoobieSpec.scala:65:13: Block result was adapted via implicit conversion (method apply) taking a by-name parameter
[error]       .query[Meeting]
[error]             ^
[error] one error found
```

The code that is failing to compile is as follows:

```scala
def loadMeeting(meetingId: MeetingId): ConnectionIO[Meeting] =
    sql"select subject, description, frequency from meeting where meeting_id = $meetingId"
      .query[Meeting]
      .unique
```

The previous method can be found in context in the following link: https://github.com/alonsodomin/cron4s/blob/8eddf262965d6ff4ec574ca1fcdde12397994248/modules/doobie/src/test/scala/cron4s/doobie/DoobieSpec.scala#L63

The code compiles in Scala 2.12, the compile error can be found in the following GitHub action log:
https://github.com/alonsodomin/cron4s/runs/3240652398?check_suite_focus=true#step:6:50

**Comment by jatcwang** [comment]
I suspect this is related to shapelss Lazy according to https://github.com/scala/bug/issues/12072

Since Doobie still supports 2.12 and probably will for a while, I don't think we can stop using `Lazy`. Does adding the flag (as suggested in the linked issue) help?

**Comment by alonsodomin** [comment]
You are right, adding the flag when using Scala 2.13 removes the problem. Thanks.
