### ISSUE TITLE
Missing specs2 scalaz package on Maven central?

### ISSUE THREAD

**Issue by randm-ch** [tpolecat/doobie#393]
`doobie-contrib-specs2` version `0.3.1-M2` has a compile time dependency to `doobie-core-cats` (see https://mvnrepository.com/artifact/org.tpolecat/doobie-contrib-specs2_2.12/0.3.1-M2). When I run my test (which contains a `check` statement) I get this error:

    Could not run test ch.randm.music4s.persistence.DoobieSpec: java.lang.NoSuchMethodError: doobie.util.update$Update0.analysis()Lcats/free/Free;

I'm a newbie to Doobie (and Scala, for that matter) so I may be wrong on this, but judging from the last part of the message I suspect that it tries to load a Cats class, which is not what this package should do, as it is supposed to work with Scalaz, right? On the other hand, there is no `doobie-contrib-specs2-cats` on Maven Central so I may be missing something.

I tried changing the dependencies in my project to use the `doobie-*-cats` packages instead, which worked fine, the test ran without problems. So is the Scalaz version of the `specs2` package missing from Maven Central for Doobie 0.3.1-M2 with Scala 2.12?

Cheers for your work, and I'm looking forward to future improvements :) Let me know if I can help you with anything here.

**Comment by tpolecat** [comment]
Hi @randm-ch yes, there was an issue with the specs2 artifacts that should be sorted now. If you try `0.3.1-SNAPSHOT` I think you'll be in business. I will release a new milestone today probably.

Note the section in the README.md on changes to the artifact/package names in the dev releases.

Let me know how it goes.

**Comment by randm-ch** [comment]
Thanks, it works with `0.3.1-SNAPSHOT` 👍 

    [info] DoobieSpec
    [info]
    [info] The Doobie Hikari transactor should
    [info]   be able to set up a table
    [info]     Update0 defined at ArtistRepository.scala:16
    [info]
    [info]       CREATE TABLE artist (
    [info]       id        SERIAL,
    [info]       name      VARCHAR NOT NULL,
    [info]       biography VARCHAR
    [info]       )
    [info]
    [info]       + SQL Compiles and Typechecks
    [info]
    [info]
    [info] Total for specification DoobieSpec
    [info] Finished in 264 ms
    [info] 1 example, 0 failure, 0 error
    [info]
    [info] Passed: Total 1, Failed 0, Errors 0, Passed 1
    [success] Total time: 185 s, completed Dec 5, 2016 11:27:03 AM
